---
- hosts: jenkins
  gather_facts: no
  vars:
    pkey: "-----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEAr3AN+CcK3HzhdlKgBEYrOXLutko3d7uMijGYiS/O9yygbk83
bdrOCPBi+pZiAKto8jCXRo+bXrAYHeqmOAxKKmqc8Ts76IPH2jHrgDzxJGM1CC8p
sOM8zyhvuTMvAZgazW2spz3u2cEbwawAv2K4nvu9CjGooD/AIatvF924vUJd3xa6
QDmI6gVtd3B856N6zzM/ceG+f1H0bnPH9MNl35g+PNJRJMGRRa3/qW9G7FG0Bf6B
VByFWfDjiLVWyp/qLj0bHRTeqbbhUCIE076wCVu8BMoZWojWRlz6K+BbNrZUceyR
hPnBQu/LmcJCR5QsQu1AEgdcAkmB9pBUhitacQIDAQABAoIBAQCKEru70SZ4L4TW
teKgWoVMWotLRo/vGNlcLfpqBglyeVnuV0Q9nlZHrMGJjO+mrUEUU2/LpdxXImpo
qTOWqv138p6AMOlObuDMdjttmwkCZV3oig3a3I0QUTfU31agf5Cgmy+mFFU2Zggt
Xezcs5qv7Vpzem/HZ0UUerMdanAp6pLoUo/NIv1/air5AloQrKNXcUbPzCct5YiT
TpqqYu/5KLuKRsQGiD7cMvfigRAWp3yuZaFaegWMYsVWn9SkT8joiuUoxiQ3cCPo
iH/TxYgB4V0A8n980vbMzu2oC/UCYrH4LzE6CRcgPdL96qcTFoWacpwgnLV7WJT2
kk71FPM9AoGBANsTBbGIwGpO6fLNvCZhqUP9mtZVK6wf//I4Y4Td47+g2AIl6Bvt
2554zZsOnczo6qsLipN4vlKeYhxX62+bTWhMSoiHhRgxoIqQu34nHMUnx3ty6hC4
6GAlje4oqXudCazY3pyw9Vl3EDPSgN+w+euxAD/5vYH5NdIb5wIaOksDAoGBAM0C
IQZqTOidEISyny8nlmw5F1W0l5UjnR7KWZbjmulStvCl3XxL+dHDO9h5hR+0Ba8b
8YF9EbHBXj0gJ+z9vLmZOhHg7BoVDvtJTDWGEPEX1zE6EpPQgKddZYpkZZtytFI3
KxVs/kUi47id1rmFZZ0JJGmNmdWMY7pXO6GbyHB7AoGBALdDanfhllVYPo1HXiYd
fKPL+0NhbG9JNatDUL1NgcBEpW7mlw0GJbqkBBu6VnecQPNlbD+BunUS2bAsPF/Y
4yBk8dTUyZo7qblA6hfWUFL9u/qhXv0uMfZ8dAbPLTijXfyiT1d1EUoOOBeh+P0n
52orX7IlEUsxVry1asJvfmRRAoGAEH3TWkjC1xOLeKFF3O06VIpjLinQ59ZtlUSB
4Hl+xLY6sTEmmBEkj5M9BTUBWIOK0YNV8iy1d68ufYxQqefffq6s1TNayt5WzjAf
SU73ne1lCji5tdpX/x6sRG2/Hrojd1moxZh2++jKmNdZpqLsga1ymGsjrOIWQ68w
xNdbUHECgYAVw2j7RDxboaLO3Y3NIBsz/b5rCqU55W4Rz5VWT8OVU3aOojc3PN9p
mlIT+GEy48Ww0/sTHrSnPyCWMmWhQgpdEVTkFNylTVZ1JvLXkLdeBLEzk9jdNCpC
868i/wCYvYUogkJ/H/UUt6mTE7NKvLM2pI1FKHK3WziMK59voA6aQw==
-----END RSA PRIVATE KEY-----"
  tasks:
    - name: Replace multi-line string variable in Groovy file
      replace:
        path: files/3_createCred.groovy
        after: 'def privateKey = """'
        regexp: ".*?"
        before: '"""\\n'
        replace: '{{ pkey }}'
      delegate_to: localhost
