- name: Prepare the prod node
  hosts: prod
  gather_facts: no 
  tasks:
    - name: Install java on the prod
      command: "sudo amazon-linux-extras install java-openjdk11 -y"
    - name: Get the slave_secret
      command: "cat .slave_secret.node1"
      register: slave_secret
      delegate_to: localhost
    - name: Get the jenkins IP
      command: "terraform -chdir=terraform output -raw jenkins_public_ip"
      register: jenkins_ip
      delegate_to: localhost
    - name: Get the agent.jar file
      get_url:
        url: "http://{{jenkins_ip.stdout}}:8080/jnlpJars/agent.jar"
        dest: /home/ec2-user/agent.jar
    - name: Set up cron job to run jenkins agent
      cron:
        name: Run agent
        minute: "*"
        job: 'nohup java -jar /home/ec2-user/agent.jar -jnlpUrl http://{{jenkins_ip.stdout}}:8080/manage/computer/node1/jenkins-agent.jnlp -secret {{slave_secret.stdout}} -workDir "/home/ec2-user" -internalDir "null" > /dev/null 2>&1 &'
    #- name: Schedule Java command to run in one minute
    #  at:
    #    command: nohup java -jar /home/ec2-user/agent.jar -jnlpUrl http://{{jenkins_ip.stdout}}:8080/manage/computer/node1/jenkins-agent.jnlp -secret {{slave_secret.stdout}} -workDir "/home/ec2-user" -internalDir "null" > /dev/null 2>&1 &
    #    count: 1
    #    units: minutes
    #  become: no
