---
- name: Configure Jenkins VM
  hosts: remote_jenkins
  gather_facts: no
  tasks:
    # Installing Jenkins
    - name: Setting jenkins repo
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo
    - name: Adding the repo key
      rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
    - name: Updating Everything
      yum:
        name: "*"
        state: latest
    - name: "Installing java-openjdk11"
      command: sudo amazon-linux-extras install java-openjdk11 -y
    - name: Installing Jenkins
      yum: 
        name: jenkins
        state: present
    - name: Enable and start jenkins
      service:
        name: jenkins
        state: started
        enabled: yes
    - name: Daemon-reload
      systemd:
        daemon_reload: yes
    - command: "sudo cat /var/lib/jenkins/secrets/initialAdminPassword"
      register: adminPass
    - name: Get the temporary adminPass
      debug:
        var: adminPass 
    # Setting Up jenkins
    - name: Create Directory init.groovy.d
      file:
        path: /var/lib/jenkins/init.groovy.d/
        state: directory
        owner: jenkins
        group: jenkins
    - name: Copy the jenkins init script
      copy:
        src: files/1_init.groovy
        dest: /var/lib/jenkins/init.groovy.d/1_init.groovy
        owner: jenkins
        group: jenkins
    - name: get the public IP of jenkins
      command: "terraform -chdir=terraform output -raw jenkins_public_ip"
      register: jenkins_ip
      delegate_to: localhost
    - name: change the jenkinsUrl in the locationconf file
      lineinfile:
        path: files/jenkins.model.JenkinsLocationConfiguration.xml
        regexp: "<jenkinsUrl>"
        line: "<jenkinsUrl>http://{{jenkins_ip.stdout}}:8080/</jenkinsUrl>"
      delegate_to: localhost
    - name: "Turn the number of executors on the Built-in node to 0" 
      lineinfile:
        path: /var/lib/jenkins/config.xml
        regexp: "<numExecutors>"
        line: "<numExecutors>0</numExecutors>"
    - name: copy the init script
      copy:
        src: files/1_init.groovy
        dest: /var/lib/jenkins/init.groovy.d/1_init.groovy
        owner: jenkins
        group: jenkins
    - name: copy the users script
      copy:
        src: files/2_userCreation.groovy
        dest: /var/lib/jenkins/init.groovy.d/2_userCreation.groovy
        owner: jenkins
        group: jenkins
    - name: copy the location conf file
      copy:
        src: files/jenkins.model.JenkinsLocationConfiguration.xml
        dest: /var/lib/jenkins/
        owner: jenkins
        group: jenkins
    - name: make sure to get the privat eIP of the prod node
      command: "terraform -chdir=terraform output -raw prod_private_ip"
      register: prod_private_ip
      delegate_to: localhost
    - name: Copy the 3_createToken.groovy
      copy:
        src: files/3_createToken.groovy
        dest: /var/lib/jenkins/init.groovy.d/3_createToken.groovy
        owner: jenkins
        group: jenkins
    - name: Restart jenkins to apply setup and create token
      service:
        name: jenkins
        state: restarted    
    - name: Get the token
      fetch:
        src: /tmp/m0d4s
        dest: ./.token.m0d4s
    - name: Get the jenkins-cli.jar
      get_url:
        url: "http://{{jenkins_ip.stdout}}:8080/jnlpJars/jenkins-cli.jar"
        dest: /home/ec2-user/jenkins-cli.jar
    - name: Cat the API_Token
      command: "cat /tmp/m0d4s"
      register: api_token
    - name: Create a conf file 
      copy:
        content: |
          <?xml version='1.1' encoding='UTF-8'?>
          <slave>
            <remoteFS>/home/ec2-user</remoteFS>
            <numExecutors>1</numExecutors>
            <mode>NORMAL</mode>
            <retentionStrategy class="hudson.slaves.RetentionStrategy$Always"/>
            <launcher class="hudson.slaves.JNLPLauncher">
              <workDirSettings>
                <disabled>false</disabled>
                <workDirPath>/home/ec2-user</workDirPath>
                <failIfWorkDirIsMissing>false</failIfWorkDirIsMissing>
              </workDirSettings>
              <webSocket>true</webSocket>
            </launcher>
          </slave>
        dest: /home/ec2-user/conf.xml
    - name: Create a new node
      shell: |
        cat /home/ec2-user/conf.xml | java -jar /home/ec2-user/jenkins-cli.jar -auth m0d4s:{{api_token.stdout}} -s http://127.0.0.1:8080/ create-node node1
      ignore_errors: yes
    - name: Get the secret 
      shell: |
        echo 'println jenkins.model.Jenkins.instance.nodesObject.getNode("node1")?.computer?.jnlpMac' | java -jar /home/ec2-user/jenkins-cli.jar -auth m0d4s:{{api_token.stdout}} -s http://127.0.0.1:8080/ groovy =
      register: slave_secret
    - name: Save that secret in case
      copy:
        content: "{{slave_secret.stdout}}"
        dest: .slave_secret.node1
      delegate_to: localhost
    

